name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          set -e
          npm ci

      - name: Build project
        env:
          VITE_APP_GEMINI: ${{ secrets.GEMINI_API_KEY }} # Use VITE_APP_GEMINI
          VITE_APP_BASE_URL: ${{ secrets.BASE_URL }} # Add other env vars as needed
        run: |
          set -e
          npm run build

      - name: Verify build output
        run: |
          echo "Listing contents of the 'dist' directory:"
          ls -al dist/

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/ # Vite's default build directory
          server-dir: /public_html/
          debug: true
